echo "ORG_SECRET_GLOBAL: $ORG_SECRET_GLOBAL"
echo "ORG_SECRET_TESTING: $ORG_SECRET_TESTING"
echo "ORG_SECRET_TESTING_CLONE: $ORG_SECRET_TESTING_CLONE"
echo "REPO_TESTING_SECRET: $REPO_TESTING_SECRET"
echo "REPO_TESTING_CLONE_SECRET: $REPO_TESTING_CLONE_SECRET"

echo "test1"
