echo "ORG_SECRET_GLOBAL: $ORG_SECRET_GLOBAL"

echo "ORG_SECRET_TESTING: $ORG_SECRET_TESTING"
echo "REPO_TESTING_SECRET: $REPO_TESTING_SECRET"
echo "REPO_TESTING_QA_SECRET: $REPO_TESTING_QA_SECRET"
echo "REPO_TESTING_PROD_SECRET: $REPO_TESTING_PROD_SECRET"

echo "ORG_SECRET_TESTING_CLONE: $ORG_SECRET_TESTING_CLONE"
echo "REPO_TESTING_CLONE_SECRET: $REPO_TESTING_CLONE_SECRET"
echo "REPO_TESTING_CLONE_QA_SECRET: $REPO_TESTING_QA_SECRET"
echo "REPO_TESTING_CLONE_PROD_SECRET: $REPO_TESTING_PROD_SECRET"

echo "test1"
