echo "ORG_GLOBAL: $ORG_GLOBAL"
echo "ORG_A1: $ORG_A1"
echo "ORG_A2: $ORG_A2"

echo "REPO_A1_GENERAL: $REPO_A1_GENERAL"
echo "REPO_A1_QA: $REPO_A1_QA"
echo "REPO_A1_PROD: $REPO_A1_PROD"

echo "REPO_A2_GENERAL: $REPO_A2_GENERAL"
echo "REPO_A2_QA: $REPO_A2_QA"
echo "REPO_A2_PROD: $REPO_A2_PROD"

echo "test2"
